### ISSUE TITLE
Unicode for python 2 ?

### ISSUE THREAD

**Issue by abdelouahabb** [saravanan-k90/python-jedi-brackets#1]
Hi, thank you first for this extension ^_^

here is the error I get:

`File "C:/Users/Abdelouahab/AppData/Roaming/Brackets/extensions/user/saravanan.python-jedi-brackets/python3_jedi.py", line 64, in <module>
    main(read)
  File "C:/Users/Abdelouahab/AppData/Roaming/Brackets/extensions/user/saravanan.python-jedi-brackets/python3_jedi.py", line 7, in main
    rd = unicode(read,'utf-8')
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 156: invalid continuation byte
`

It is because of `read = json.loads(read)` that doesent accept unicode.

And, it doesent work here for windows, even putting the right path (`C:/Python27/python.exe`) which returns the same in the console after using `console.log`

**Comment by saravanan-k90** [comment]
I am really sorry I didn't test in windows due to lack of system. Please can you suggest any solution that would work in windows. I would test the same in linux and release a patch immediately.

**Comment by saravanan-k90** [comment]
@abdelouahabb , I googled regarding....... 'utf8' codec can't decode byte 0xe9
I think 0xe9 is a latin char which utf-8 can't decode.
[unicodedecodeerror-invalid-continuation-byte](https://stackoverflow.com/questions/5552555/unicodedecodeerror-invalid-continuation-byte). Any suggestion/solution ?

**Comment by abdelouahabb** [comment]
@saravanan-k90 I think this bug happens when we dont know which encoding we are using, while trying to convert it to `utf-8`

I was trying to debug the result, and got this error:

`Uncaught SyntaxError: Unexpected token [`

This happened when I tried to catch the content of the stream:

    def main(read):
        print read
        read = json.loads(read)

**Comment by saravanan-k90** [comment]
Can you try?

    def main(read):
      read.decode('utf-8')
      read = json.loads(read)

**Comment by abdelouahabb** [comment]
I tried this, doesent work, now, I try to solve the problem about normal ASCII text, because the completion doesent work here, here is what I got from debug:

`read
Out[73]: u'{"source":"\n# coding: utf-8\nimport json\nimport jedi\nimport sys\n\ndef main(read):\n    read = json.loads(read)\n    print read\n\n    if read["type"] == "goto":\n        payload = goto_def(read["source"], read["line"], read["column"], read["path"])\n        payload = json.dumps(payload)\n\n    else:\n        payload = completions(read["source"], read["line"], read["column"], read["path"])\n        payload = json.dumps(payload)\n    \ndef completions(source, line, column, path):\n    script = jedi.api.Script(\n        source = source,\n        line = line + 1,\n        column = column,\n        path = path\n    )\n\n    completions = []\n\n    try:\n        for completion in script.completions():\n            completions.append(completion.name)\n\n        return completions\n    except:\n        return []\n\ndef goto_def(source, line, column, path):\n\n    try:\n        script = jedi.api.Script( source, line , column ,path)\n        defs = script.goto_definitions()\n    except:\n        return []\n\n    if defs:\n        is_built = script.goto_definitions()[0].in_builtin_module()\n        module_name = script.goto_definitions()[0].module_name\n\n    defs_string = list()\n    for get in defs:\n        defs_string.append({\n            "module_path": get.module_path,\n            "line": get.line,\n            "column":get.column,\n            "is_built_in": is_built,\n        })\n        break\n\n    return defs_string\n\nif __name__ == "__main__": \n    read = sys.argv[1]\n    main(read)\n","line":1,"column":0,"path":"C:/Users/Abdelouahab/AppData/Roaming/Brackets/extensions/user/saravanan.python-jedi-brackets/python3_jedi.py","type":"autocomplete"}'`

and then, using  `json.loads(read)` I got the error:

`JSONDecodeError: Invalid control character u'#' at: line 2 column 1 (char 12)`

Maybe this is the problem ?

**Comment by saravanan-k90** [comment]
No Json decode error is due to invalidly decoded string. what is the readout you get without decoding?

**Comment by abdelouahabb** [comment]
Here is what I get from the source (without being sent to python)
![sans titre](https://cloud.githubusercontent.com/assets/2527234/12451716/35ae3d34-bf8b-11e5-999e-1e4602eb968b.png)

**Comment by saravanan-k90** [comment]
This string is passed as sys argument, to get related auto complete strings. what about in python. Does it display the old (UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 156: invalid continuation byte).

**Comment by abdelouahabb** [comment]
Yes, the problem about unicode still exists, but the problem is even ASCII doesent work

**Comment by abdelouahabb** [comment]
What I tried to do, is inserting an `utf-8`, but supposing that the stream came normally to python, so I can see if there is a problem about `json.loads()`, tried this, and dident got the problem:

    read = ur'''{"source":"\n# é coding: utf-8\nimport json\nimport jedi\n\nimport sys\n\n\ndef main(read):\n    a = read.decode('utf-8')\n    print a\n    read = json.loads(read)\n    print read\n\n    if read[\"type\"] == \"goto\":\n        payload = goto_def(read[\"source\"], read[\"line\"], read[\"column\"], read[\"path\"])\n        payload = json.dumps(payload)\n\n    else:\n        payload = completions(read[\"source\"], read[\"line\"], read[\"column\"], read[\"path\"])\n        payload = json.dumps(payload)\n    \ndef completions(source, line, column, path):\n    script = jedi.api.Script(\n        source = source,\n        line = line + 1,\n        column = column,\n        path = path\n    )\n\n    completions = []\n\n    try:\n        for completion in script.completions():\n            completions.append(completion.name)\n\n        return completions\n    except:\n        return []\n\ndef goto_def(source, line, column, path):\n\n    try:\n        script = jedi.api.Script( source, line , column ,path)\n        defs = script.goto_definitions()\n    except:\n        return []\n\n    if defs:\n        is_built = script.goto_definitions()[0].in_builtin_module()\n        module_name = script.goto_definitions()[0].module_name\n\n    defs_string = list()\n    for get in defs:\n        defs_string.append({\n            \"module_path\": get.module_path,\n            \"line\": get.line,\n            \"column\":get.column,\n            \"is_built_in\": is_built,\n        })\n        break\n\n    return defs_string\n\nif __name__ == \"__main__\": \n    read = sys.argv[1]\n    main(read)\n","line":4,"column":0,"path":"C:/Users/Abdelouahab/AppData/Roaming/Brackets/extensions/user/saravanan.python-jedi-brackets/python3_jedi.py","type":"autocomplete"}'''

    json.loads(read)
    Out[105]: 
    {u'column': 0,
    u'line': 4,
    u'path': u'C:/Users/Abdelouahab/AppData/Roaming/Brackets/extensions/user/saravanan.python-jedi-brackets/python3_jedi.py',
    u'source': u'\n# \xe9 coding: utf-8\nimport json\nimport jedi\n\nimport sys\n\n\ndef main(read):\n    a = read.decode(\'utf-8\')\n    print a\n    read = json.loads(read)\n    print read\n\n    if read["type"] == "goto":\n        payload = goto_def(read["source"], read["line"], read["column"], read["path"])\n        payload = json.dumps(payload)\n\n    else:\n        payload = completions(read["source"], read["line"], read["column"], read["path"])\n        payload = json.dumps(payload)\n    \ndef completions(source, line, column, path):\n    script = jedi.api.Script(\n        source = source,\n        line = line + 1,\n        column = column,\n        path = path\n    )\n\n    completions = []\n\n    try:\n        for completion in script.completions():\n            completions.append(completion.name)\n\n        return completions\n    except:\n        return []\n\ndef goto_def(source, line, column, path):\n\n    try:\n        script = jedi.api.Script( source, line , column ,path)\n        defs = script.goto_definitions()\n    except:\n        return []\n\n    if defs:\n        is_built = script.goto_definitions()[0].in_builtin_module()\n        module_name = script.goto_definitions()[0].module_name\n\n    defs_string = list()\n    for get in defs:\n        defs_string.append({\n            "module_path": get.module_path,\n            "line": get.line,\n            "column":get.column,\n            "is_built_in": is_built,\n        })\n        break\n\n    return defs_string\n\nif __name__ == "__main__": \n    read = sys.argv[1]\n    main(read)\n',
     u'type': u'autocomplete'}

So, the problem is not in `json.loads()` method

**Comment by saravanan-k90** [comment]
reset python3_jedi.py code to default. try adding utf-8 header at the start of the file you work and then check whether autocomplete works.

**Comment by abdelouahabb** [comment]
but how about the string sent from node? can you capture it? because from python side, even using the `é` that worked, which means, the problem comes from what node send to python.

**Comment by saravanan-k90** [comment]
python3_jedi.py prints the autocomplete data., which i capture it in jedidomain.js  child.stdout.

The error you talked about, 

    File "C:/Users/Abdelouahab/AppData/Roaming/Brackets/extensions/user/saravanan.python-jedi-     brackets/python3_jedi.py", line 64, in <module> main(read) File    "C:/Users/Abdelouahab/AppData/Roaming/Brackets/extensions/user/saravanan.python-jedi-  brackets/python3_jedi.py", line 7, in main rd = unicode(read,'utf-8') UnicodeDecodeError: 'utf8' codec   can't decode byte 0xe9 in position 156: invalid continuation byte

There is no such line 7 in python3_jedi.py i had wrote.

I am not able to understand the issue you are facing clearly. Also i cannot support this extension for windows., due to lack of system for now. Send a pull request if you clear it.

**Comment by abdelouahabb** [comment]
Ok, I will try to solve that problem on windows and make a patch ^_^
