### ISSUE TITLE
Autocompletion duplicates partial input if ends with underscore

### ISSUE THREAD

**Issue by jpcaram** [saravanan-k90/python-jedi-brackets#2]
If I input `my_` and select `my_name` from the suggestions list, the results in the editor becomes `my_my_name`. This only seems to happen if the last character in the hint is `_`.

Using plugin version 0.1.2, Brackets version 1.6.0-16680.

**Comment by saravanan-k90** [comment]
Sorry @jpcaram I am not continuing support for this extension. Fork it.......

**Comment by saravanan-k90** [comment]
@jpcaram Sorry for my past comment. I deleted it. I didn't check the extension @Brackets version 1.6.0-16680. I have my pc issues., which i think will soon be recovered within this week. I'll soon query you regarding  `last character` `_` issue. If you have found any solution send pull request., i'll test and update it.

**Comment by saravanan-k90** [comment]
@jpcaram - I have fixed the issue. Please update the extension and check.

**Comment by jpcaram** [comment]
Excellent. Thank you. I will try it soon.

So you will continue to develop this plugin? I already have too much on my plate.

**Comment by jpcaram** [comment]
It's working properly now. Thanks.

**Comment by saravanan-k90** [comment]
I will continue support and fix issues for this plugin.
