### ISSUE TITLE
Usage of Ctrl+J instead of Ctrl+Alt+J

### ISSUE THREAD

**Issue by Wikunia** [saravanan-k90/python-jedi-brackets#3]
Thanks for your extension. Is there any reason why you not the default shortcut for jump to definition, which is Ctrl+J?

**Comment by saravanan-k90** [comment]
Not any particular reason. It seems no one used that key combination in other extensions., so i used it.

**Comment by Wikunia** [comment]
Why are you not using `Ctrl+J` ? ;)

**Comment by saravanan-k90** [comment]
If you want to use `Ctrl+J` [change gotokey](https://github.com/saravanan-k90/python-jedi-brackets/blob/master/main.js#L28) and use it.
