### ISSUE TITLE
Uncaught TypeError: Cannot read property 'trim' of null

### ISSUE THREAD

**Issue by ficristo** [saravanan-k90/python-jedi-brackets#4]
If I write `de` the autocomplete for `def` come out correctly.
But when I explicit ask for autocomplete with "Ctrl+Spacebar" on OSX I hit this error:
`main.js:89 Uncaught TypeError: Cannot read property 'trim' of null`

**Comment by saravanan-k90** [comment]
i am extremely sorry @ficristo., my position is bad now(no job, less money, less internet, old linux system)... so i may not be able to try to check or solve the issue you have opened. But i really appreciate for opening issue in the plugin.
